### ISSUE TITLE
Small typo in `acrostiche` package README

### ISSUE THREAD

**Issue by JKRhb** [typst/packages#25]
Trying to use the example in the README.md file of the `acrostiche` package, I noticed that there is currently a small typo (`#init-acromyns(acronyms)` instead of `#init-acronyms(acronyms)`) preventing it from working right away.

CC @Grisely

**Comment by Grisely** [comment]
Yep, dyslexia will do that to you. I'll fix it for the next version thanks for letting me know.
(I'll also provide a title argument as per your comment on the PR).

**Comment by laurmaedje** [comment]
> Yep, dyslexia will do that to you. I'll fix it for the next version thanks for letting me know.

Note that we have updated our rules regarding this. Small doc fixes that cannot affect the behaviour of the library are now allowed even after submission. (Typically they do not affect the library, but it could happen if the library `read()`s its README. Then it would be forbidden.)

**Comment by Grisely** [comment]
> 

What about adding a feature? I want to provide users with the ability to change a heading body that I initially arbitrarily fixed. I think it is a good feature to have, and it would not be a breaking change (the current heading body would become the default). Is that allowed?

**Comment by laurmaedje** [comment]
Any changes to the code would require a new version. A user who already has a cached version of the package on their machine couldn't access the new features otherwise. Apart from that it also feels a bit too dangerous and strange. This policy is really only about fixing minor docs things that went unnoticed. But publishing a new version with a minor new feature is absolutely fine.

**Comment by laurmaedje** [comment]
Fixed in acrostiche:0.2.0.
