### ISSUE TITLE
acrostiche in a show rule

### ISSUE THREAD

**Issue by astrale-sharp** [typst/packages#35]
it would be neat if you could define a show rule instead of calling `#accr` functions.

show rules cannot support the following syntax yet but let it be food for thoughts :

```
show: x if x in accronym_list.map(get_short_version) => {
          if already been used {
                     use short version
          } else { use long version }
}
```

**Comment by astrale-sharp** [comment]
@Grisely

**Comment by Grisely** [comment]
Originally the acronym call was in a reference (@BIOS for example), which made it much closer to natural writing. I agree that a show rule would be even nicer, but both approaches share the same issue, in my opinion, to try to be smarter than you.
I am not sure I was a show rule to try and guess which word I want to be expanded because there might be a reason why I specifically want the acronym to be in the short version.
I might also want the plural version, and I find it weird to not have a similar syntax for the singular and plural versions.
Finally, one of the main hurdles I had to overcome with the package was how the variables were shared between the main document and the package. I suspect show rules would not play nicely in that regard.

I agree that the syntax could be even lighter, but for now, I did not find a solution that does not compromise on features and predictability of the results. I am, of course, open to suggestions and on the lookout for ways to improve the package.

**Comment by Marmare314** [comment]
> show rules cannot support the following syntax yet but let it be food for thoughts

This actually works:
```typ
#let x = "abc"
#show x: "xyz"
Test abc 123
```
So it should be possible to define a show rule for each acronym this way.

> I might also want the plural version, and I find it weird to not have a similar syntax for the singular and plural versions.

I just want to mention that you can also use the supplement in reference show rules. So that you could have `@NN[s]` expand to `Neural Networks`. 

> Finally, one of the main hurdles I had to overcome with the package was how the variables were shared between the main document and the package. I suspect show rules would not play nicely in that regard.

There should not be much issue in that. You can just return a  "show rule" (ie a function `content -> content`) that the user has to apply. All global package variables should then still be accessible in that function. Although I haven't tried this out, so maybe I'm missing something.

**Comment by laurmaedje** [comment]
There's probably no good alternative here because `acrostiche` has no `repository` key in its manifest, but in general I would prefer to keep issues on this repository only related to the package management itself and not the packages.

**Comment by JKRhb** [comment]
> There's probably no good alternative here because `acrostiche` has no `repository` key in its manifest, but in general I would prefer to keep issues on this repository only related to the package management itself and not the packages.

A bit off-topic but: Should the `repository` key maybe become mandatory for future packages/versions? Otherwise, people will probably always create issues here due to the lack of a better alternative.

**Comment by laurmaedje** [comment]
Not everybody necessarily develops their stuff in a repository though.

**Comment by Grisely** [comment]
Thank you for your ideas. I am adding a final point to better explain my view, and then we can move that to the fork repo: https://github.com/Grisely/packages.

My point is not that it would not be possible but that it could introduce unwanted behaviour to have a show rule trigger on every instance of a work it recognizes.
In the case where the show rule triggers a regex of an acronym and lookup the definition, I am almost sure I can find counter-examples to every possible regex definition of an acronym. So I don't trust a regex to catch my acronyms.
In the case where you define one show rule per acronym, this seems like a burden to put on the user, and that would make the package heavier to use.
Even if it works, what about the case where the first instance is in a table that automatically locates at the top of the page, but you want to keep the acronym short? Do you have to manually escape each instance of the acronym that you want to keep short (kinda defeats the purpose of an automatic acronym management system IMHO).

Finally, for the "s" at the end of the reference, it is indeed possible but the whole purpose of having a plural version of the definition is to be able to have something different than just an "s" at the end (more important in languages other than English where the noun could be at the beginning, like French).

All in all the current solution is, in my opinion, the best compromise between features, practicality, and determinism of the behaviour.
